includes:
  - ../templates/camera_default.yaml
  - ../templates/integrator_path.yaml
  - ../templates/campose_sphere.yaml

Project: MultiView
project_name: multiview_pbr
output_folder: ./result/examples

Scene:
  type: CustomScene
  source_path: ./resources/examples
  scale: 1.0

  element:
    - type: pbr_mesh
      name: hero_object
      mesh_filename: cow.ply
      albedo_filename: cow_albedo.png
      roughness_filename: uniform_roughness.png
      metalness_filename: uniform_metallic.png
    - type: envmap_light
      envmap_filename: envmap.exr
      scale: 1.0
      z_up: true

gen_normal: true
gen_depth: false
gen_roughness: true
gen_metallic: true
record_camera: true
log_extri_mat_type: opencv
