includes:
  - ../templates/camera_default.yaml
  - ../templates/integrator_path.yaml
  - ../templates/campose_sphere.yaml

Project: MultiView
project_name: multiview_transparent
output_folder: ./result/examples

Scene:
  type: CustomScene
  source_path: ./resources/examples
  scale: 1.0

  element:
    - type: transparent_mesh
      name: hero_object
      mesh_filename: cow.ply
      IoR: 1.5
      reflection_flag: true
    - type: envmap_light
      envmap_filename: envmap.exr
      scale: 1.0
      z_up: true

CamPose:
  phi_num: 12

gen_normal: true
gen_depth: false
record_camera: true
log_extri_mat_type: opencv
