includes:
  - ../templates/camera_default.yaml
  - ../templates/integrator_path.yaml

Project: PlanarCalibration
project_name: calibration_demo
output_folder: ./result/examples

Scene:
  type: CustomScene
  source_path: ./resources/examples

  element:
    - type: textured_rectangle
      name: checkerboard
      texture_filename: checkerboard_9_12.png
      scale: [1.2, 0.9, 1]
    - type: envmap_light
      envmap_filename: envmap.exr
      scale: 1.0
      z_up: true

CamPose:
  type: SinglePose
  target: [0, 0, 0]
  theta: 45
  phi: 50
  r: 3.0
  up: [0, 0, 1]
  shift: [0, 0, 0]
