includes:
  - ../templates/camera_default.yaml
  - ../templates/integrator_path.yaml
  - ../templates/campose_single.yaml

Project: MultiView
project_name: show_white_raw_demo
output_folder: ./result/examples

Scene:
  type: CustomScene
  source_path: ./resources/examples

  element:
    - type: raw
      name: hero_object
      payload:
        type: ply
        filename: ./resources/examples/shape/cow.ply
        bsdf:
          type: diffuse
          reflectance: 0.6
    - type: raw
      name: env_light
      payload:
        type: envmap
        filename: ./resources/examples/env_map/envmap.exr
        scale: 1.0
        to_world:
          type: rotation
          axis: [1, 0, 0]
          angle: 90

record_camera: false
